config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }

  root to: 'pages#intern_me'
  resources :questions
  resources :posts

  get '/me' => 'pages#me'
  get '/mycode' => 'pages#mycode'
  get '/exchanges' => 'pages#exchanges'
  get '/hobbies' => 'pages#hobbies'
  get '/education' => 'pages#education'
  get '/skills' => 'pages#skills'
  get '/more' => 'pages#more'
  get '/resume' => 'pages#resume'
  get '/websites' => 'pages#websites'
  get '/github' => 'pages#github'
  get '/travel' => 'pages#travel'
  get '/volunteer' => 'pages#volunteer'

  get '/imprint' => 'imprints#imprint'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :description

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/imprints_controller.rb
class ImprintsController < ApplicationController

def show
  render params[:id]
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def show
  render params[:id]
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  helper_method :collection, :resource

def index
end

def new
  @post = Post.new
end

def show
  @post = Post.find(params[:id])
end

def edit
  @post = Post.find(params[:id])
  @post.save!
end

def update
  @post = Post.find(params[:id])
  @post.update!(permitted_params)
  render :show
end

def create
  @post = Post.new(permitted_params)
  if @post.save
    redirect_to @post, notice: 'ok!'
  else
    render :new
  end
end

protected

def permitted_params
  params.require(:post).permit(:title, :description, :timestamp, :answer)
end

# def post_creation_params
#   permitted_params.merge({
#     user_id: current_user.id
#   })
# end

def collection
  @post ||= Post.all
end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  helper_method :collection, :resource

def index
  @questions = Question.order("updated_at ASC")
end

def new
  @question = Question.new
end

def show
  @question = Question.find(params[:id])
end

def edit
  @question = Question.find(params[:id])
  @question.save!
end

def update
  @question = Question.find(params[:id])
  @question.update!(permitted_params)
  render :show
end

def create
  @question = Question.new(permitted_params)
  if @question.save
    redirect_to @question, notice: 'ok!'
  else
    render :new
  end
end

protected

def permitted_params
  params.require(:question).permit(:title, :description, :timestamp, :answer)
end

# def question_creation_params
#   permitted_params.merge({
#     user_id: current_user.id
#   })
# end

def collection
  @question ||= Question.all
end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super
  end

  def update
    super
  end

  protected

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  helper_method :collection

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_params)
    if @user.save
      redirect_to @user, notice: 'ok!'
    else
      render :new
    end
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def collection
    @users ||= User.all
  end

  def permitted_params
    params.require(:user).permit(:email, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title [aboutnina]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Ubuntu:400,700", :rel => "stylesheet", :type => "text/css"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %script{:src => "js/jquery-1.11.0.min.js"}
    = favicon_link_tag '/img/favicon.ico'
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} [aboutnina]
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.current
              = link_to ('Home'), root_path
            %li
              %a{:href => "#information"} Work and Education
            %li
              %a{:href => "#experience"} Experience
            %li
              %a{:href => "#skills"} Skills
            %li
              %a{:href => "#statement"} Personal Statement
            %li
              = link_to ('Questions'), questions_path
            %li
              = link_to ('Posts'), posts_path
            / %li
            /   %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            /     Travelling and Exchange
            /     %span.caret
            /   %ul.dropdown-menu{:role => "menu"}
            /     %li
            /       = link_to t('Travelled To'), travel_path
            /     %li
            /       = link_to t('Exchange Experience'), exchanges_path
            / %li.dropdown
            /   %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            /     Hobbies and Volunteering
            /     %span.caret
            /   %ul.dropdown-menu{:role => "menu"}
            /     %li
            /       = link_to t('Hobbies'), hobbies_path
            /     %li
            /       = link_to t('Volunteering'), volunteer_path

          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to t('Contact'), me_path
            %li
              = link_to t('Imprint'), imprint_path
            %li
              - if user_signed_in?
                = link_to 'Log out', destroy_user_session_path, method: :delete

.container
  = yield
  = flash[:notice] || flash[:message]
  .container
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"}
            &times;
          = content_tag :div, msg, :id => "flash_#{name}"
  %footer
    .navbar.navbar-inverse.navbar-fixed-bottom
      .container
        %p.navbar-text.lefter Site Built By Nina
        %p.navbar-text.pull-right
          %a{:href => "https://github.com/BerliNinja", target: :blank } Link To GitHub

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59171052-1', 'auto');
  ga('send', 'pageview');

:javascript
  // <![CDATA[
  $('.navbar').onePageNav({
           currentClass: 'active',
           changeHash: true,
           scrollSpeed: 1200
           });
  // ]]>

app/views/pages/education.html.haml
%h2 [ Education ]
%h4
  Aug 06 - Jul 07
%h5
  High-School-Year
V Lyceum Ogolnoksztalcacy Dabrowa Gornicza

%hr

%h4
  Aug 07 - Jul 09
%h5
  Higher education entrance qualification (A-levels)
Rosa-Luxemburg-Gymnasium Berlin

%hr

%h4
  Oct 09 – Jul 13
%h5
  Bachelor of Science in Urban Planning
Technical University Berlin, Berlin (Germany)

%hr

%h4
  Aug 13– Jul 16
%h5
  IT Specialist, Application Development EQF level 5
Berlin College of Further Education for Information Technology and Medical Equipment Technology, Berlin (Germany)
%h6 General
%ul
  %li
  %li Economic and Social Studies
  %li Business Economics
%h6 Occupational
%ul
  %li Technical English
  %li Applicationdevelopment
  %li IT-Systems
  %li Linux

app/views/pages/exchanges.html.haml
%h2 [ Exchange Experience ]
%h4 Aug 06 -July 07

%p High-School-Year in Poland

app/views/pages/hobbies.html.haml
hobbies n stuff

app/views/pages/intern_me.html.haml
.row
  .col-xs-4.text-center
    %h1 NINA STACHE
    %h4 Apprentice Web-Development
    %img.big.img-circle{:src => "/img/me/nina2.jpg", :style => "display:block;"}/

  .col-xs-7.col-xs-offset-1
    .row.links
      %h1.text-center INTERNSHIP ME!
    .row
      .col-xs-3.col-xs-offset-1.circle.red
        %li= link_to 'My Resume', '#information'
      .col-xs-3.col-xs-offset-1.circle.yellow
        %li= link_to 'My Experience', '#work'
      .col-xs-3.col-xs-offset-1.circle.green
        %li= link_to 'My Skills', '#skills'
    .row

    / %h4.text-center Personal Statement
    / %img.border{:src => "/img/border.jpg"}
    / %p I am an apprentice in Application Development interested in an internship abroad as a Software Developer for up to four months.

    / %p Ruby and Ruby on Rails was a great start for me to learn to code and I was lucky to take part in a RailsGirls workshop and visited a ruby conference in Lyon (RuLu) already. That is why I want to deepen my Ruby and RoR skills in a company working with RoR as well as to exchange knowledge and experiences. I am used to motivating myself, working with new topics and learning a lot within a short time.
    / %p I contribute to improve my companies official websites by solving front- and backend tasks, including database handling, implementation of front end changes using mainly HAML and SASS, writing migration scripts and much more. I was able to acquire a good understanding of the MVC and how a Rails application functions. In my spare time I try to improve my coding skills as well- recently I started to work on this personal website and try to implement other little projects.

    %blockquote
      %p I want to be an intern in your company for three months and deepen my Ruby on Rails skills. I am eager to learn as quickly as possible and can start flexibly beginning from July 2015.

      %footer
        Nina Stache
        %cite{:title => "Source Title"} 23/02/2015
    %blockquote
      %p I am an apprentice in web development working with Ruby on Rails, Ruby, haml, sass, javascript, postgresql, rspec and many more. I have hands-on knowledge of all these for a little over one year.

      %footer
        Nina Stache
        %cite{:title => "Source Title"} 23/02/2015


    %li
      = link_to "Read More...", more_path
.light-blue
  #information.section
    .row
      %h1.text-center RESUME
      .col-xs-2
        %div.circle.yellow
          %li
            = link_to ('Professional Info'), resume_path
      .col-xs-10
        %ul.list-inline
          %li.btn.btn-lg.btn-danger Nina Juliane Stache
          %li.btn.btn-lg.btn-info 25
          %li.btn.btn-lg.btn-primary Berlin/Germany
          %li.btn.btn-lg.btn-success NinaStache[at]gmx.de
          %li.btn.btn-lg.btn-warning
            = link_to 'xing', "https://www.xing.com/profile/Nina_Stache", target: :blank
        / %table
        /   %tr
        /     %td Name:
        /     %td Nina Stache
        /   %tr
        /     %td Age:
        /     %td 25
        /   %tr
        /     %td Born and Lives in:
        /     %td Berlin
        /   %tr
        /     %td E-Mail:
        /     %td NinaStache [at] gmx.de
        /   %tr
        /     %td Skype:
        /     %td nina.stache
        /   %tr
        /     %td Xing:
        /     %td= link_to 'xing', "https://www.xing.com/profile/Nina_Stache", target: :blank
        /   %tr
        /     %td Language:
        /     %td Ruby

  #information.section
    .row
      .col-xs-2
        %div.circle.yellow
          %li
            = link_to ('Work Experience'), resume_path
      .col-xs-10

        %h4
          Dec 2012 - Jul 2013
        %h5
          Student Employee Engineering Performance Office
        %h5
          Company: Bombardier Transportation, Hennigsdorf (Germany)
        %p Worked on complex projects such as:Generic Work Packages
        %p Reorganization of Organizational Charts
        %p Support of the Head of Engineering Performance Office
        %p Research and implementation of project management software

        %br
        %h4
          Apr 2014 – Present
        %h5
          Apprentice IT Specialist, Application Development
        %h5
          Company: Absolventa - Employment Website, Berlin (Germany) Developing our main application which includes:
        %p Solving front-end tasks with HTML and CSS
        %p Backend development with Ruby and Ruby on Rails(currently version 4.1)
        %p Implementation of UX optimised changes
        %p Developing internal web application
        %p Writing and reviewing code
        %p Writing migration scripts and pushing changes

        %br
        %h4
          Aug 2013 – Mar 2014
        %h5
          Apprentice IT Specialist, Application Development
        %h5
          Company: DEMOS Gesellschaft für E-Partizipation, Berlin (Germany)
        %p Introduction into electrical engineering
        %p HTML and CSS
        %p Build LaTeX templates

        %br
        %h4
          Aug 2009 – Oct 2009
        %h5
          Intern
        %h5
          Company: Senate administration for urban development, Berlin (Germany)
        %p Maintenance of database
        %p Participation and recording during meeting



  #information.section
    .row
      .col-xs-2
        %div.circle.yellow
          %li
            = link_to ('Education'), resume_path
      .col-xs-10
        %h4
          Aug 2013– Jul 2016
        %h5
          IT Specialist, Application Development EQF level 5
        Berlin College of Further Education for Information Technology and Medical Equipment Technology, Berlin (Germany)
        %h5 General
        %p Economic and Social Studies
        %p Business Economics
        %h5 Occupational
        %p Technical English
        %p Applicationdevelopment
        %p IT-Systems
        %p Linux

        %br
        %h4
          Oct 2009 – Jul 2013
        %h5
          Bachelor of Science in Urban Planning
        Technical University Berlin, Berlin (Germany)

        %h4
          Aug 2007 - Jul 2009
        %h5
          Higher education entrance qualification (A-levels)
        Rosa-Luxemburg-Gymnasium Berlin

        %h4
          Aug 2006 - Jul 2007
        %h5
          High-School-Year
        V Lyceum Ogolnoksztalcacy Dabrowa Gornicza
.green-blue
  #experience.section
    .row
      %h2.text-center MY EXPERIENCE
      .col-xs-2
        %div.circle.red
          %li Working
      .col-xs-10
        %h4 Working @ Absolventa
        %p During weekdays I work at Absolventa where I contribute to the development of following websites:
        %ul
          %li
            = link_to 'Absolventa', 'http://www.absolventa.de', target: 'blank'
          %li
            = link_to 'Praktikum-Info', 'http://www.praktikum.info', target: 'blank'
          %li
            = link_to 'Trainee-Geflüster', 'http://www.trainee-gefluester.de', target: 'blank'
          %li
            = link_to 'Jobmesse-Radar', 'http://www.jobmesse-radar.de', target: 'blank'
    .row
      .col-xs-2
        %div.circle.red
          %li Developing
      .col-xs-10
        %h4 Developing in my free time
        %p In my spare time I try to work on my own projects as often as I can. Feel free to visit my GitHub account:
        = link_to 'Nina bei GitHub', 'https://github.com/BerliNinja', target: 'blank'
        %p I regularly attend meetups like the Ruby-Learners Meetup @ Fairmondo:
        = link_to 'Ruby Co-Learning', 'http://www.meetup.com/opentechschool-berlin/events/219754230/', target: 'blank'
        %p I visited a Rails-Girls-Event
        = link_to 'Rails Girls Berlin', 'http://railsgirlsberlin.de/', target: 'blank'
        %p And I went to a Ruby Conference, namely the RuLu conference in Lyon in May 2014
        = link_to 'My blogpost about the ruby-conference', 'http://stayinginberlin.blogspot.de/2014_06_01_archive.html', target: 'blank'

#skills.section
  .row
    %h2.text-center PERSONAL SKILLS

    %table.table.table-bordered.table-striped.table
      %thead
        %tr
          %th Language
          %th Understanding
          %th Reading
          %th Writing

      %tbody
        %tr.success
          %td English
          %td C1
          %td B2
          %td B2
        %tr.warning
          %td German
          %td mothertongue
          %td mothertongue
          %td mothertongue
        %tr.danger
          %td Polish
          %td B2
          %td B2
          %td B1
        %tr.info
          %td French
          %td A2
          %td A1
          %td A1
  .dark
    .row
      %h4 Communication Skills
      %p
        Excellent organizational and communicational skills gained through volunteer work with pupils for a students exchange organization (YFU-Germany) for 8 years.
        This includes the organization, thematic preparation and implementation of three to five workshops per day, being responsible for 50 adolescents and sleepless nights spending with debriefings and the organization for the next day.

    .row
      %h4 Occupational Skills
      %ul
        %li Good command of office suite
        %li Experience with unix command-line tools
        %li HTML5, HAML, CSS3, SASS, javascript
        %li Basic understanding of relational databases
        %li Ruby on Rails
        %li Ruby
        %li Basic knowledge of C#
        %li Experience using git for source-control
        %li Experience with SCRUM methodology
        %li TDD

#statement.section
.row
  %h2 PERSONAL STATEMENT
  %p
  I am a 25 years old apprentice in Application Development interested in an internship abroad as a Software Developer for up to four months.
  Until two years ago I had no experience in coding at all (please don't stop reading now) but after finishing my Bachelor’s degree in Urban Planning in 2013 I knew I wanted to go for something completely new, something extremely challenging and exciting. I decided: if I want to start all over I don't want to go to University again but rather learn everything I need hands-on in a company environment.
  %p
  That is why in 2013 I began an apprenticeship which includes full-time employment in a company (in my case it is Absolventa http://www.absolventa.de/) and attending vocational school every three to five weeks for a whole week. Until now I don't regret my decision at all but I am quite aware of how much I have to learn. That is why I would love to get the opportunity to broaden my knowledge in another company and getting to know other procedures and working in another cultural environment.
  %p
  When I applied for my apprenticeship I was lucky to come upon Absolventa, the company that decided to hire me even though I had no further experience in coding, but who were willing to support a young woman to enter the big world of web development. Ruby and Ruby on Rails was a great start for me to learn to code and I was lucky to take part in a RailsGirls workshop and visited a ruby conference in Lyon (RuLu) already. That is why I want to deepen my Ruby and RoR skills in a company working with RoR as well as to exchange knowledge and experiences. I am used to motivating myself, working with new topics and learning a lot within a short time.
  %p
  So far I contribute to improving my companies official websites by solving front- and backend tasks, including database handling, implementation of front end changes using mainly HAML and SASS, writing migration scripts and much more. I was able to acquire a good understanding of the MVC and how a Rails application functions. In my spare time I try to improve my coding skills as well - recently I started working on a personal website and am trying to implement other little projects. From time to time I go to meet-ups listening to talks about related topics. So far I haven’t specialized in a subject as our development team is quite small and I have a broad range of tasks to work on, which is why I have no specific preferences what to work on exactly but I do want to gain a deeper insight into a specific field.

.row
  .col-xs-11.col-xs-offset-1
    %p
    %div.circle.red.col-xs-4
      %li= link_to 'My Resume', resume_path
    %div.circle.yellow.col-xs-4
      %li= link_to 'My Work', mycode_path
    %div.circle.green.col-xs-4
      %li= link_to 'My Skills', skills_path
  .row
    .row
      .row
/ %h2 Welcome
/ %h4 This is my personal website mainly created for my applications for an internship

/ %p Feel free to check out the CV Part and everything else you're interested in. This is the place where you can ask any question which were not answered in all the other menu points.

/ = link_to "Neue Frage stellen", new_question_path



/ - collection.each do |question|
/   %h4 Question
/   = question.title
/   %h4 Description
/   = question.description
/   = link_to "Frage bearbeiten", edit_question_path(question)

app/views/pages/me.html.haml
%h1 Contact
%img.border{:src => "/img/border.jpg"}
%div.info
  %div.circle
    %li Professional Info
  %table
    %tr
      %td Name:
      %td Nina Stache
    %tr
      %td Age:
      %td 25
    %tr
      %td Born and Lives in:
      %td Berlin
    %tr
      %td E-Mail:
      %td NinaStache [at] gmx.de
    %tr
      %td Skype:
      %td nina.stache
    %tr
      %td Xing:
      %td= link_to 'xing', "https://www.xing.com/profile/Nina_Stache", target: :blank
    %tr
      %td Facebook:
      %td
    %tr
      %td Language:
      %td Ruby

app/views/pages/more.html.haml
.row
  %h2 PERSONAL STATEMENT
  %p
  I am a 25 years old apprentice in Application Development interested in an internship abroad as a Software Developer for up to four months.
  Until two years ago I had no experience in coding at all (please don't stop reading now) but after finishing my Bachelor’s degree in Urban Planning in 2013 I knew I wanted to go for something completely new, something extremely challenging and exciting. I decided: if I want to start all over I don't want to go to University again but rather learn everything I need hands-on in a company environment.
  %p
  That is why in 2013 I began an apprenticeship which includes full-time employment in a company (in my case it is Absolventa http://www.absolventa.de/) and attending vocational school every three to five weeks for a whole week. Until now I don't regret my decision at all but I am quite aware of how much I have to learn. That is why I would love to get the opportunity to broaden my knowledge in another company and getting to know other procedures and working in another cultural environment.
  %p
  When I applied for my apprenticeship I was lucky to come upon Absolventa, the company that decided to hire me even though I had no further experience in coding, but who were willing to support a young woman to enter the big world of web development. Ruby and Ruby on Rails was a great start for me to learn to code and I was lucky to take part in a RailsGirls workshop and visited a ruby conference in Lyon (RuLu) already. That is why I want to deepen my Ruby and RoR skills in a company working with RoR as well as to exchange knowledge and experiences. I am used to motivating myself, working with new topics and learning a lot within a short time.
  %p
  So far I contribute to improving my companies official websites by solving front- and backend tasks, including database handling, implementation of front end changes using mainly HAML and SASS, writing migration scripts and much more. I was able to acquire a good understanding of the MVC and how a Rails application functions. In my spare time I try to improve my coding skills as well - recently I started working on a personal website and am trying to implement other little projects. From time to time I go to meet-ups listening to talks about related topics. So far I haven’t specialized in a subject as our development team is quite small and I have a broad range of tasks to work on, which is why I have no specific preferences what to work on exactly but I do want to gain a deeper insight into a specific field.

.row
  .col-md-11.col-md-offset-1
    %p
    %div.circle.red.col-md-4
      %li= link_to 'My Resume', resume_path
    %div.circle.yellow.col-md-4
      %li= link_to 'My Work', mycode_path
    %div.circle.green.col-md-4
      %li= link_to 'My Skills', skills_path

app/views/pages/mycode.html.haml
.row
  %h2.text-center MY EXPERIENCE
  .row
    .col-md-2
      %div.circle.yellow
        %li Working
    .col-md-10
      %h4 Working @ Absolventa
      %p During weekdays I work at Absolventa where I contribute to the development of following websites:
      %ul
        %li
          = link_to 'Absolventa', 'http://www.absolventa.de'
        %li
          = link_to 'Praktikum-Info', 'http://www.praktikum.info'
        %li
          = link_to 'Trainee-Geflüster', 'http://www.trainee-gefluester.de'
        %li
          = link_to 'Jobmesse-Radar', 'http://www.jobmesse-radar.de'
  .row
    .col-md-2
      %div.circle.yellow
        %li Developing
    .col-md-10
      %h4 Developing in my free time
      %p In my spare time I try to work on my own projects as often as I can. Feel free to visit my GitHub account:
      = link_to 'Nina bei GitHub', 'https://github.com/BerliNinja', target: 'blank'

app/views/posts/index.html.haml
%h2 Priorly Posted Articles
%li
  = link_to 'New Post', new_post_path, :class => "btn btn-info"
- collection.each do |p|
  .jumbotron
    %div
      %h2 Title:
      = p.title

    %div
      %h2 Description:
      = p.description

      %p
      Created:
      = p.created_at
      Updated:
      = p.updated_at

      %p
      = link_to "Edit Post", edit_post_path(p), :class => "btn btn-danger btn-full"

app/views/posts/show.html.haml
- if @resource
  %h2 Current Post
  .jumbotron
    %div.circle-small
      %li Post
      %p
      Title:
      = @resource.title
      %p
      Created:
      = @resource.created_at
      %p
      Updated:
      = @resource.updated_at
      %p
      = link_to "Edit Question", edit_question_path(q), :class => "btn btn-danger btn-full"
    %hr
    %div.circle-small
      %li Description
      %p
      Description:
      = @resource.description
      %p
      Created:
      = @resource.created_at
      %p
      Updated:
      = @resource.updated_at
      %p
      = link_to "Edit Description", edit_question_path(q), :class => "btn btn-danger btn-full"

app/views/questions/index.html.haml
.questions
  %h2 Questions
  %img.border{:src => "/img/border.jpg"}
  %h4 You are very welcome to ask me a question
  %h4 ↓↓↓↓↓↓↓↓↓↓↓↓↓
  %li
    = link_to 'New Question', new_question_path, :class => "btn btn-info"

  %h2 Priorly Asked Questions
  - collection.each do |q|
    .jumbotron
      %h3 Question
      %h4
        Title:
        = q.title
      %p
      Created:
      = q.created_at
      Updated:
      = q.updated_at
      %p
      = link_to "Edit Question", edit_question_path(q), :class => "btn btn-danger btn-full"

      %h3 Description
      %h5
        Description:
        = q.description
      %p
      = link_to "Edit Description", edit_question_path(q), :class => "btn btn-danger btn-full"

      %h3 Answer
      %h4
        Answer:
        = q.answer
      %p
      Created:
      = q.created_at
      Updated:
      = q.updated_at
      %p
      - if current_user
        - if current_user.email="ninastache@gmx.de"
          %li
            = link_to "Answer Question", edit_question_path(q), :class => "btn btn-full btn-danger"

app/views/questions/show.html.haml
- if @resource
  %h2 Priorly Asked Questions
  .jumbotron
    %div.circle-small
      %li Question
      %p
      Title:
      = @resource.title
      %p
      Created:
      = @resource.created_at
      %p
      Updated:
      = @resource.updated_at
      %p
      = link_to "Edit Question", edit_question_path(q), :class => "btn btn-danger btn-full"
    %hr
    %div.circle-small
      %li Description
      %p
      Description:
      = @resource.description
      %p
      Created:
      = @resource.created_at
      %p
      Updated:
      = @resource.updated_at
      %p
      = link_to "Edit Description", edit_question_path(q), :class => "btn btn-danger btn-full"

    %hr
    %div.circle-small
      %li Answer
      Answer:
      =@resource.answer
      %p
      Created:
      = @resource.created_at
      %p
      Updated:
      = @resource.updated_at
      %p
    - if current_user.email="dazwiebel@web.de"
      = link_to "Answer Question", edit_question_path(q), :class => "btn btn-full btn-danger"